export const brand = {
  maroon: '#68111B',
  maroonDark: '#3F0A11',
  saffron: '#F59E0B',
  amber: '#FBBF24',
  sun: '#FFD600',
  cream: '#FFFBE8',
  paper: '#FFFFFF',
  ink: '#24191A',
  muted: '#76676A',
  line: '#EADFD8',
  success: '#287A55',
  info: '#315C88',
};

export const divineTheme = {
  token: {
    colorPrimary: brand.maroon,
    colorInfo: brand.info,
    colorSuccess: brand.success,
    colorWarning: brand.saffron,
    colorError: '#B42318',
    colorText: brand.ink,
    colorTextSecondary: brand.muted,
    colorBorder: brand.line,
    colorBgLayout: '#F8F5EF',
    colorBgContainer: brand.paper,
    borderRadius: 12,
    borderRadiusLG: 18,
    controlHeight: 42,
    fontFamily: "Inter, 'Noto Sans Devanagari', system-ui, sans-serif",
    boxShadowSecondary: '0 10px 30px rgba(63, 10, 17, 0.08)',
  },
  components: {
    Button: {
      borderRadius: 10,
      fontWeight: 700,
      primaryShadow: '0 6px 16px rgba(104, 17, 27, 0.18)',
    },
    Card: {
      borderRadiusLG: 18,
      paddingLG: 22,
    },
    Menu: {
      itemBorderRadius: 10,
      itemHeight: 44,
      itemMarginBlock: 4,
      itemSelectedBg: '#FFF1D6',
      itemSelectedColor: brand.maroon,
      itemHoverBg: '#FFF8E8',
    },
    Input: { activeBorderColor: brand.saffron, hoverBorderColor: brand.saffron },
    Select: { activeBorderColor: brand.saffron, hoverBorderColor: brand.saffron },
    DatePicker: { activeBorderColor: brand.saffron, hoverBorderColor: brand.saffron },
    Tabs: { itemSelectedColor: brand.maroon, inkBarColor: brand.saffron },
    Table: { headerBg: '#FBF7F0', headerColor: brand.maroonDark },
  },
};
