import React, { useEffect, useState } from 'react';
import { useMutation, useQuery } from '@apollo/client';
import { Badge, Button, Card, Checkbox, Col, Empty, Input, List, Row, Select, Skeleton, Switch, Tabs, Tag, Typography } from 'antd';
import { BellOutlined, CheckOutlined, ClockCircleOutlined, DeleteOutlined } from '@ant-design/icons';
import { DELETE_REMINDER_SCHEDULE_MUTATION, MARK_ALL_NOTIFICATIONS_READ_MUTATION, NOTIFICATION_CENTRE_QUERY, SAVE_REMINDER_SCHEDULE_MUTATION, SET_NOTIFICATION_STATUS_MUTATION, UPDATE_NOTIFICATION_PREFERENCES_MUTATION } from '../graphql/operations';

const { Title, Paragraph, Text } = Typography;
const allDays = [{label:'Sun',value:0},{label:'Mon',value:1},{label:'Tue',value:2},{label:'Wed',value:3},{label:'Thu',value:4},{label:'Fri',value:5},{label:'Sat',value:6}];

export default function NotificationCentre() {
  const { data, loading, error, refetch } = useQuery(NOTIFICATION_CENTRE_QUERY, { fetchPolicy: 'cache-and-network' });
  const [setStatus] = useMutation(SET_NOTIFICATION_STATUS_MUTATION);
  const [markAll] = useMutation(MARK_ALL_NOTIFICATIONS_READ_MUTATION);
  const [updatePreferences] = useMutation(UPDATE_NOTIFICATION_PREFERENCES_MUTATION);
  const [saveReminder] = useMutation(SAVE_REMINDER_SCHEDULE_MUTATION);
  const [deleteReminder] = useMutation(DELETE_REMINDER_SCHEDULE_MUTATION);
  const [prefs, setPrefs] = useState(null);
  const [reminder, setReminder] = useState({ label: '', localTime: '08:00', daysOfWeek: [1,2,3,4,5,6,0], channel: 'push', enabled: true });
  const [notice, setNotice] = useState('');
  useEffect(() => { if (data?.myNotificationPreferences) setPrefs({ ...data.myNotificationPreferences, __typename: undefined, id: undefined }); }, [data]);
  if (loading && !data) return <Card><Skeleton active /></Card>;
  if (error) return <Empty description="Notification centre could not be loaded." />;
  const inbox = data?.myNotifications;
  const items = [
    { key:'inbox', label:<span><BellOutlined /> Inbox <Badge count={inbox?.unreadCount || 0} /></span>, children:<div className="notification-panel"><div className="notification-toolbar"><div><Title level={3}>Your notifications</Title><Paragraph>Programme updates and reminders in one calm place.</Paragraph></div><Button icon={<CheckOutlined />} disabled={!inbox?.unreadCount} onClick={async()=>{await markAll(); await refetch();}}>Mark all read</Button></div>{inbox?.items?.length ? <List dataSource={inbox.items} renderItem={(item)=><List.Item className={`notification-row ${item.status}`} actions={[item.status==='unread'?<Button type="link" onClick={async()=>{await setStatus({variables:{id:item.id,status:'read'}});refetch();}}>Mark read</Button>:null,<Button type="link" onClick={async()=>{await setStatus({variables:{id:item.id,status:'archived'}});refetch();}}>Archive</Button>]}><List.Item.Meta avatar={<div className="notification-icon"><BellOutlined /></div>} title={<><Text strong>{item.title}</Text>{item.status==='unread'?<Tag color="orange">New</Tag>:null}</>} description={<><Paragraph>{item.body}</Paragraph><small>{new Date(item.createdAt).toLocaleString()}</small></>} /></List.Item>} />:<Empty description="You are all caught up." />}</div>},
    { key:'preferences', label:'Preferences', children:prefs?<Card className="preference-card"><Title level={3}>Delivery preferences</Title><Paragraph>Transactional service messages remain separate from optional marketing consent.</Paragraph>{[['pushEnabled','Push notifications'],['emailEnabled','Email updates'],['whatsappEnabled','WhatsApp reminders'],['marketingAllowed','Optional marketing']].map(([key,label])=><div className="preference-row" key={key}><Text>{label}</Text><Switch checked={Boolean(prefs[key])} onChange={(value)=>setPrefs({...prefs,[key]:value})} /></div>)}<Row gutter={12}><Col xs={24} sm={8}><Text>Quiet starts</Text><Input value={prefs.quietStart || ''} placeholder="22:00" onChange={(e)=>setPrefs({...prefs,quietStart:e.target.value||null})}/></Col><Col xs={24} sm={8}><Text>Quiet ends</Text><Input value={prefs.quietEnd || ''} placeholder="07:00" onChange={(e)=>setPrefs({...prefs,quietEnd:e.target.value||null})}/></Col><Col xs={24} sm={8}><Text>Timezone</Text><Input value={prefs.timezone} onChange={(e)=>setPrefs({...prefs,timezone:e.target.value})}/></Col></Row><Button type="primary" onClick={async()=>{await updatePreferences({variables:{input:prefs}});setNotice('Preferences saved.');refetch();}}>Save preferences</Button></Card>:null},
    { key:'reminders', label:<span><ClockCircleOutlined /> Reminders</span>, children:<div className="reminder-layout"><Card><Title level={3}>Create reminder</Title><Input value={reminder.label} placeholder="Morning practice" onChange={(e)=>setReminder({...reminder,label:e.target.value})}/><Input value={reminder.localTime} placeholder="08:00" onChange={(e)=>setReminder({...reminder,localTime:e.target.value})}/><Select value={reminder.channel} options={[{value:'push',label:'Push'},{value:'email',label:'Email'},{value:'whatsapp',label:'WhatsApp'},{value:'in_app',label:'In app'}]} onChange={(channel)=>setReminder({...reminder,channel})}/><Checkbox.Group options={allDays} value={reminder.daysOfWeek} onChange={(daysOfWeek)=>setReminder({...reminder,daysOfWeek})}/><Button type="primary" onClick={async()=>{await saveReminder({variables:{input:reminder}});setReminder({...reminder,label:''});setNotice('Reminder saved.');refetch();}}>Add reminder</Button></Card><div>{data?.myReminderSchedules?.length?data.myReminderSchedules.map((item)=><Card key={item.id} className="reminder-card"><Tag>{item.channel}</Tag><Title level={4}>{item.label}</Title><Text>{item.localTime} · {item.daysOfWeek.map((day)=>allDays.find((d)=>d.value===day)?.label).join(', ')}</Text><Button danger type="text" icon={<DeleteOutlined />} onClick={async()=>{await deleteReminder({variables:{id:item.id}});refetch();}}>Delete</Button></Card>):<Empty description="No reminders created yet." />}</div></div>},
  ];
  return <div className="notification-centre"><Tag>STAY CONNECTED</Tag><Title>Notifications & reminders</Title>{notice?<div className="library-notice">{notice}</div>:null}<Tabs items={items} /></div>;
}
